### PR TITLE
68 paths tsconfig created

### LINKED ISSUE #68: create path on TSconfig

### PR DESCRIPTION
**Pull request by DanielMJSilva**
Path created:

``
    "paths": {
      "@/*": ["./*"],
      "components/*": ["./src/components/*"],
      "styles/*": ["./src/styles/*"],
      "images/*": ["./public/images/*"],
      "types/*": ["./src/types/*"],
    }
``

### CODE REVIEW

**Review by rmc3408 — COMMENTED** [review]
By convention, add `@` at beginning. 

remove the first one. '@/'
missing utils folder
missing data folder
missing asset folder

**Comment by rmc3408** [comment]
By convention, add `@` at beginning. 

remove the first one. '@/'
missing utils folder
missing data folder
missing asset folder

**Comment by rmc3408** [comment]
Complete to link your PR information please, and follow PR convention.

**Comment by rmc3408** [comment]
Also, Mark all devs to review!!!

**Comment by DanielMJSilva** [comment]
All changes done.
Only the path from types that breaks when @ is added, so I skipped this one.

**Comment by rmc3408** [comment]
You need to review the whole code.

yes. types exist in globals.  
so, lets change folder name for @typing

**Review by JWMedeiros — APPROVED** [review]
Looks Good after changes.

**Review by rmc3408 — COMMENTED** [review]
did you check test folder?

**Review by DanielMJSilva — COMMENTED** [review]
All good

**Review by sergiobtos — APPROVED** [review]
LGTM! just fix the conflict and we are good.

**Pull request merged**
