### PR TITLE
49-Adding how to use .env instructions

### LINKED ISSUE #49: ENV docs frontEnd

### PR DESCRIPTION
**Pull request by sergiobtos**
Summary of Changes:
A dedicated frontend env file template was created to indicate the env variables in the repositories. A readme file was also modified on how to create and use the template and where to find the value for each key.
A test file was created as well.

### CODE REVIEW

**Review by rmc3408 — APPROVED** [review]
I think it is great. Just about naming branch. I tried to make more simple, just ticket issue and ticket description. More details you can find onboard docs, naming branch and semantic commits.

LGTM.

**Comment by rmc3408** [comment]
Sorry. Another point is to fill out your pull request information as much as possible .. so we can track after like by milestones, development 

This is a PR , so label is PR. .. bellow milestone, there is a filed development.. link your ticket there.

**Comment by rmc3408** [comment]
Sorry, unit test is failing.

**Comment by sergiobtos** [comment]
> I think it is great. Just about naming branch. I tried to make more simple, just ticket issue and ticket description. More details you can find onboard docs, naming branch and semantic commits.
> 
> LGTM.

Done

**Comment by sergiobtos** [comment]
> Sorry. Another point is to fill out your pull request information as much as possible .. so we can track after like by milestones, development
> 
> This is a PR , so label is PR. .. bellow milestone, there is a filed development.. link your ticket there.

@rmc3408  can you check now ? Am I still missing something ?

**Comment by sergiobtos** [comment]
> Sorry, unit test is failing.

I delete the test file for this. It won't work. let's keep testing only for components.

**Comment by rmc3408** [comment]
> > Sorry, unit test is failing.
> 
> I delete the test file for this. It won't work. let's keep testing only for components.

Yes. I was thinking to keep unit Testing just for simple functions (like adding two arguments and returning the sum) ... very simple just for everyone learned how to use it.

**Review by rmc3408 — APPROVED** [review]
LGTM. Done

**Pull request merged**
